### ISSUE TITLE
使用 cmder 快速启动模板后无法使用自定义命令 user_aliases.cmd

### ISSUE THREAD

**Issue by eve2ptp** [doglex/Light_Weapon#2]

**Comment by doglex** [comment]
回滚到上个版本试试呢  https://github.com/doglex/Light_Weapon/commit/2a2a0e5f4e5a84ab803ef9a09657591db9493ab6

**Comment by eve2ptp** [comment]
问题解决，顺便问一下为什么在 init.bat 加这一行不生效
```python
set "user_aliases=%CMDER_CONFIG_DIR%\user_aliases.cmd"
```

**Comment by doglex** [comment]
> 问题解决，顺便问一下为什么在 init.bat 加这一行不生效
> 
> ```python
> set "user_aliases=%CMDER_CONFIG_DIR%\user_aliases.cmd"
> ```

可能不能这样set，可能得把user_aliases.cmd文件里的内容直接拷到init.bat里，比如直接加上
alias ll=ls -alh --color=auto

**Comment by doglex** [comment]
> 问题解决，顺便问一下为什么在 init.bat 加这一行不生效
> 
> ```python
> set "user_aliases=%CMDER_CONFIG_DIR%\user_aliases.cmd"
> ```

是不是目录的问题 
call "%cmder_root%\config\user_aliases.cmd"
这里的  %cmder_root% 可能得填写绝对路径，或者改成
call "%CMDER_CONFIG_DIR%\user_aliases.cmd"
